import{a as P,S as q,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const E="53375249-7d769a3dfab07f88475703207",R="https://pixabay.com/api/",f=15;async function g(n,t=1){const r={key:E,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:t};return(await P.get(R,{params:r})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more-btn"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function M(){m.innerHTML=""}function y(n){const t=n.map(({webformatURL:r,largeImageURL:s,tags:e,likes:o,views:i,comments:w,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${r}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function b(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function S(){p.classList.remove("is-hidden")}function l(){p.classList.add("is-hidden")}const $=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let u="",c=1,d=0;l();$.addEventListener("submit",x);O.addEventListener("click",A);async function x(n){n.preventDefault();const t=n.currentTarget,r=t.elements["search-text"].value.trim();if(!r){a.error({message:"Please enter a search query!",position:"topRight"});return}u=r,c=1,d=0,M(),l(),b();try{const s=await g(u,c),e=s.hits;if(d=s.totalHits??0,!e||e.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(e),d>f?S():(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),t.reset()}}async function A(){c+=1,l(),b();try{const t=(await g(u,c)).hits;if(!t||t.length===0){a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}y(t);const r=document.querySelector(".gallery li");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}c*f>=d?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
